### ISSUE TITLE
Library update from 6.5.2 to 6.6.0 cause crash

### ISSUE THREAD

**Issue by sakismts** [airbnb/lottie-android#2568]
After updating to 6.6.0 my app crashes with the error:
java.lang.NoSuchMethodError: No static method LottieAnimation(Lcom/airbnb/lottie/LottieComposition;Lkotlin/jvm/functions/Function0;Landroidx/compose/ui/Modifier;ZZZLcom/airbnb/lottie/RenderMode;ZLcom/airbnb/lottie/compose/LottieDynamicProperties;Landroidx/compose/ui/Alignment;Landroidx/compose/ui/layout/ContentScale;ZZLjava/util/Map;Lcom/airbnb/lottie/AsyncUpdates;ZLandroidx/compose/runtime/Composer;III)V in class Lcom/airbnb/lottie/compose/LottieAnimationKt; or its super classes (declaration of 'com.airbnb.lottie.compose.LottieAnimationKt'

works fine with 6.5.2

**Comment by gpeal** [comment]
@sakismts Can you attach a project that reproduces this?

**Comment by inorichi** [comment]
This is due to a [binary incompatibility](https://github.com/airbnb/lottie-android/commit/5deb2deeb3507a39fca4ee17d29e45113302b93e#diff-45404571538034dcd06d2d2ff889b3d6e148a696cee0b84b2c6e9b6ae812597b) between 6.5.1 and 6.6.0 because a new parameter was added on that composable function.

Any code compiled against 6.5.1 or lower is not compatible with a 6.6.0 runtime version. You must ensure all your dependencies using lottie to compile against either of those versions.

But I'd suggest the lottie team to add the previous `LottieAnimation` signature that just delegates to the new one, because they added a breaking change in a minor version.
